# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'NewsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for NewsDemo

end

target 'TTNewsSDK' do

  pod 'AFNetworking'
  pod 'YYModel'
  pod 'YYWebImage'
  pod 'FMDB', '~> 2.6.2' # 必须指定版本号为2.6.2 否则导入GYDataCenter就报错
  pod 'GYDataCenter'
  pod 'MJRefresh'
end
